# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50ee7c95ce06597210f978899c088bc3e337cef4b7bd61dfab1aa6ce75f83a96fc7c628f6a41a22c5d710e3ff876dd4fc75f9ceb59de21653595056ce3287fed

test:
  secret_key_base: 22fb7b5bc51814a3d2737510bc3546ce0be30681804c3050fe8e7ae32a0d7bd681378cf624dbf282525545c2dfc6693c5103f3b508100efa7401464e3059bac0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 22fb7b5bc51814a3d2737510bc3546ce0be30681804c3050fe8e7ae32a0d7bd681378cf624dbf282525545c2dfc6693c5103f3b508100efa7401464e3059bac0
